name: Deploy code from Github to Linux VM using SSH

on:
  push:
    branches:
      - codepushaws

env:
  HOST: 13.233.29.91
  USERNAME: root
  PASSWORD: 12345

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code from Github repository
      uses: actions/checkout@v2

    - name: Deploy code to Linux VM using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.HOST }}
        username: ${{ env.USERNAME }}
        password: ${{ env.KEY }}
        script: |
           mkdir -p /var/www/html
           rsync -avz . ${USERNAME}@${HOST}:/var/www/html
