name: Deploy to VM

on:
  push:
    branches:
      - codepushaws

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Deploy code
      run: |
        sshpass -p ${{ secrets.PASSWORD }} \
        scp -P 22 -o StrictHostKeyChecking=no \
        -r ./* subha@35.225.247.143:/var/www/html/
