name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy via FTPS
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          server: ftps://waws-prod-blu-431.ftp.azurewebsites.windows.net
          username: ${{ secrets.AZUREFTP_USER }}
          password: ${{ secrets.AZUREFTP_PASSWORD }}
          local-dir: /
          remote-dir: /site/wwwroot
