name: Deploy code from Github to Linux VM using SSH

on:
  push:
    branches:
      - codepushaws



jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code from Github repository
      uses: actions/checkout@v2

    - name: Deploy code to Linux VM using SSH
      uses: appleboy/ssh-action@master
      with:
        host: 13.233.29.91
        username: subha
        password: 12345
        script: |
           sudo mkdir -p /var/www/html
           sudo rsync -avz . ${USERNAME}@${HOST}:/var/www/html
