name: Push code to VM using SSH

on:
  push:
    branches:
      - codepushaws

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Push code to VM
        uses: easingthemes/ssh-deploy@v1
        with:
          host: 35.225.247.143
          port: 22
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: .
          target: /var/www/html
          flags: '-avz --delete'
